chore(bazzite-rollback-helper): reimplement "list_images" subcommand

diff --git a/system_files/desktop/shared/usr/bin/bazzite-rollback-helper b/system_files/desktop/shared/usr/bin/bazzite-rollback-helper
--- a/system_files/desktop/shared/usr/bin/bazzite-rollback-helper
+++ b/system_files/desktop/shared/usr/bin/bazzite-rollback-helper
@@ -1,7 +1,7 @@
 #!/bin/bash
 
-image="$(echo $2 | cut -d ':' -f1)"
-branch="$(echo $2 | cut -d ':' -f2)"
+image="$(echo "$2" | cut -d ':' -f1)"
+branch="$(echo "$2" | cut -d ':' -f2)"
 
 IMAGE_INFO="/usr/share/ublue-os/image-info.json"
 DEFAULT_IMAGE=$(jq -r '."image-name"' < $IMAGE_INFO)
@@ -17,10 +17,10 @@ This tool aims to help with rollbacks and rebases
 Usage: bazzite-rollback-helper [OPTION] [ARGUMENT]
 
 Options:
-  list      List available Bazzite images, Default is "$DEFAULT_BRANCH"
-  rollback  Rolls back to previously installed Bazzite image. alias for "rpm-ostree rollback"
-  current   Show currently active Bazzite image
-  rebase    Rebase/rollback to specified Bazzite image, Default is $DEFAULT_IMAGE:$DEFAULT_BRANCH
+  list [BRANCH]      List available Bazzite images, Default is "$DEFAULT_BRANCH"
+  rollback           Rolls back to previously installed Bazzite image. alias for "rpm-ostree rollback"
+  current            Show currently active Bazzite image
+  rebase             Rebase/rollback to specified Bazzite image, Default is $DEFAULT_IMAGE:$DEFAULT_BRANCH
 
 Examples:
   bazzite-rollback-helper list stable
@@ -38,14 +38,23 @@ EOF
 )
 
 
+##  List images with a specified tag
+##
+##  INPUTS:
+##    $1    Branch we want to get tags from.
+##          Fallbacks to $DEFAULT_BRANCH
+function list_images() {
+  local branch=${1:-$DEFAULT_BRANCH}
+  local regex='.Tags[]'
+  regex="$regex"\ ' | select(test("^PLACEHOLDER|^PLACEHOLDER-(?:\\d+\\.\\d+|\\d+)"))'
+  regex=${regex//PLACEHOLDER/$branch}
+  echo -e >&2 "Listing images for $branch\nThis can take a bit of time..."
+  skopeo list-tags docker://ghcr.io/ublue-os/bazzite | jq -r "$regex"
+}
+
 if [[ "$1" == "list" ]]; then
-  if [ -z "$2" ]; then
-      echo "Listing images for $DEFAULT_BRANCH"
-      skopeo list-tags docker://ghcr.io/ublue-os/bazzite | grep -E "\"$DEFAULT_BRANCH-[0-9]+\.[0-9]+|-$DEFAULT_BRANCH-[0-9]+" | sort -rV
-  else
-      echo "Listing images for $2"
-      skopeo list-tags docker://ghcr.io/ublue-os/bazzite | grep -E "\"$2-[0-9]+\.[0-9]+|-$2-[0-9]+" | sort -rV
-  fi
+  list_images "${@:2}"
+  exit
 
 elif [[ "$1" == "rollback" ]]; then
   rpm-ostree rollback
