feat(hhd): apply with fallback hhd bootc updater to steam

diff --git a/system_files/deck/shared/usr/libexec/os-branch-select b/system_files/deck/shared/usr/libexec/os-branch-select
--- a/system_files/deck/shared/usr/libexec/os-branch-select
+++ b/system_files/deck/shared/usr/libexec/os-branch-select
@@ -1,6 +1,15 @@
 #!/usr/bin/bash
 set -e
 
+if [ -x hhd.steamos ]; then
+  hhd.steamos steamos-select-branch --fallback $@
+  ret=$?
+  # If ret is not 20, exit with the return code, otherwise continue
+  if [ $ret -ne 20 ]; then
+    exit $ret
+  fi
+fi
+
 source /etc/os-release
 
 if [[ $# -eq 1 ]]; then
