feat(hhd): apply with fallback hhd bootc updater to steam (#1968)
* feat(hhd): apply with fallback hhd bootc updater to steam

* chore: move set -e below dangerous area

diff --git a/system_files/deck/shared/usr/libexec/os-branch-select b/system_files/deck/shared/usr/libexec/os-branch-select
--- a/system_files/deck/shared/usr/libexec/os-branch-select
+++ b/system_files/deck/shared/usr/libexec/os-branch-select
@@ -1,4 +1,14 @@
 #!/usr/bin/bash
+
+if [ -x hhd.steamos ]; then
+  hhd.steamos steamos-select-branch --fallback $@
+  ret=$?
+  # If ret is not 20, exit with the return code, otherwise continue
+  if [ $ret -ne 20 ]; then
+    exit $ret
+  fi
+fi
+
 set -e
 
 source /etc/os-release
